title: Indra, tu guÃ­a!
logo: /assets/img/feo-circle-aegm.jpg
description: Elige tu actividad â›° <br> piensa una fecha ðŸ“… <br> y cuÃ©ntamelo por [Whatsapp](https://wa.me/+34686569323)!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jemoji
