title: Indra, your guide!
logo: /assets/img/feo-circle-aegm.jpg
description: |
  ğŸ“œ Certified Climbing Guide
  ğŸªª Mountain Guides Union (NÂº 2041)
  ğŸ¦‹ Passionate biologist

  ğŸ¥ Acc. Ins: OM-MIC (ESDV2100035)
  âš–ï¸ CL Ins: Berkley (PIJ150CKI534)
  ğŸ· Active Tourism (soon)

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jemoji
