title: Indra, your guide!
logo: /assets/img/feo-circle-aegm.jpg
description: |
  Over 20 years of experience in hiking <br>
  and 15 years of rock-climbing. <br>
  Devoted to guiding! <br>
  <br>
  ğŸ“œ Certified Climbing Guide <br>
  ğŸªª Mountain Guides Union (NÂº 2041) <br>
  ğŸ¦‹ Passionate biologist <br>
  <br>
  ğŸ¥ Acc. Ins: OM-MIC (ESDV2100035) <br>
  âš–ï¸ CL Ins: Berkley (PIJ150CKI534) <br>
  ğŸ· Active Tourism (soon) <br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jemoji
